# Generated by Django 5.2.1 on 2025-06-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_core_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expend',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.core')),
                ('count', models.IntegerField(verbose_name='مقدار به تومان')),
                ('desc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس فاکتور')),
            ],
            bases=('core.core',),
        ),
    ]
