# Generated by Django 5.2.1 on 2025-06-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expend',
            options={'verbose_name': 'هزینه', 'verbose_name_plural': 'هزینه ها'},
        ),
    ]
