# Generated by Django 5.2.1 on 2025-06-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_core_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('core_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.core')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price_shop', models.IntegerField(verbose_name='قیمت خرید')),
                ('price', models.IntegerField(verbose_name='قیمت فروش')),
                ('count', models.IntegerField(verbose_name='تعداد موجود')),
            ],
            options={
                'verbose_name': 'ایتم',
                'verbose_name_plural': 'ایتم ها',
            },
            bases=('core.core',),
        ),
    ]
