# Generated by Django 5.2.1 on 2025-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('desc', models.CharField(max_length=1000, verbose_name='توضیحات')),
                ('image', models.FileField(upload_to='media/Menu_Item', verbose_name='عکس محصول')),
            ],
        ),
    ]
