# Generated by Django 5.2.1 on 2025-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'ایتم', 'verbose_name_plural': 'ایتم ها'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_shop',
            field=models.IntegerField(default=1, verbose_name='قیمت فروش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(verbose_name='قیمت خرید'),
        ),
    ]
