# Generated by Django 5.2.1 on 2025-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuItem', '0002_alter_menuitem_options_menuitem_price_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد موجود'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price_shop',
            field=models.IntegerField(verbose_name='قیمت خرید'),
        ),
    ]
