# Generated by Django 5.2.1 on 2025-06-12 11:44

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuItem', '0002_menuitemcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemcount',
            options={'verbose_name': 'تعداد افزودنی', 'verbose_name_plural': 'تعداد افزودنی ها'},
        ),
        migrations.AlterField(
            model_name='menuitemcount',
            name='created_by',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
        ),
    ]
