# Generated by Django 5.2.1 on 2025-06-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelmodel',
            options={'verbose_name': 'پنل', 'verbose_name_plural': 'پنل'},
        ),
    ]
