# Generated by Django 5.2.1 on 2025-06-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expend', '0002_alter_expend_options'),
        ('order', '0001_initial'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmodel',
            name='expend',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expend.expend', verbose_name='هزینه مرتبط'),
        ),
        migrations.AlterField(
            model_name='panelmodel',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderitem', verbose_name='آیتم سفارش'),
        ),
    ]
