# Generated by Django 5.2.1 on 2025-06-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_panelmodel_expend_alter_panelmodel_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmodel',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف سفارش'),
        ),
    ]
