# Generated by Django 5.2.1 on 2025-06-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_panelmodel_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelmodel',
            name='discount',
        ),
    ]
