# Generated by Django 5.2.1 on 2025-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.IntegerField(choices=[(0, 'کارت خوان'), (1, 'کارت به کارت'), (2, 'نقدی')], default=0, verbose_name='روش پرداخت'),
        ),
    ]
